language: python

sudo: false

install:
    pip install tox

script: tox

notifications:
  on_success: change
  on_failure: always

matrix:
  include:
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - python: 3.10
      env: TOXENV=py310
    - python: 3.11
      env: TOXENV=py311
    - python: 3.8
      env: TOXENV=py38 REQUESTS_VERSION="===2.2.1"
    - python: 3.9
      env: TOXENV=py39 REQUESTS_VERSION="===2.2.1"
    - python: 3.10
      env: TOXENV=py310 REQUESTS_VERSION="===2.2.1"
    - python: 3.11
      env: TOXENV=py311 REQUESTS_VERSION="===2.2.1"
    - python: pypy
      env: TOXENV=pypy REQUESTS_VERSION="===2.2.1"
    - env: TOXENV=py38-flake8
      python: 3.8
    - env: TOXENV=docstrings
    - env: TOXENV=docs
    - env: TOXENV=readme
